<a href="https://colab.research.google.com/github/VictorTiciano/ml2023-VictorTiciano/blob/master/2019/01-Pre-processamento_Limpeza_Analise_de_Dados/3%20-%20Tipos%20e%20Convers%C3%A3o%20de%20tipos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

Mostra os tipos que o numpy suporta, como fazer conversão de tipos e como identificar o tipo de um array.

In [1]:
import numpy as np

In [2]:
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [4]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [5]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [6]:
z.astype(float)

array([0., 1., 2.])

In [7]:
np.int8(z)

array([0, 1, 2], dtype=int8)

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [8]:
z.dtype

dtype('uint8')